import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const getApiCall = createApi({
  reducerPath: "getApiCall",
  baseQuery: fetchBaseQuery({
    baseUrl:  "https://dummyjson.com/c/",
  }),
  endpoints: (builder) => ({
    getData: builder.query({
      query: () => ({
        url: "ca8f-756c-40af-b116", //End-points
        method: "get", // could be get or post
      }),
    }),
  }),
});

//Autogenerated hook
export const { useGetDataQuery } = getApiCall;
